"""Add image_url to Item model

Revision ID: 20a1f1fb0d20
Revises: 0f292ef7dfe6
Create Date: 2025-11-14 16:01:31.793266

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '20a1f1fb0d20'
down_revision = '0f292ef7dfe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'image_url')
    # ### end Alembic commands ###
